/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package selfordering.apllication;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import menu_item_classes.*;
import heap_classes.MaximumPreparationTimeHeap;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Hirantha perera
 */
public class HOME1 extends javax.swing.JFrame implements Runnable{

    // implement runneble to run didgital clock inside the program while proagm is running
    int hour,second,minute;
    boolean pizza_button_state=false;
    boolean appetizer_button_state=false;
    boolean beverage_button_state=false;
    boolean dessert_button_state=false;
    
    MenuItemLinkedList original_menu_list = new MenuItemLinkedList();
    MenuItemLinkedList menu_list = new MenuItemLinkedList();
    MaximumPreparationTimeHeap max_heap = new MaximumPreparationTimeHeap(100);

    DefaultTableModel tbl_cart;
    public HOME1() 
    {
        initComponents();
        // these code for adjest coloum width
        TableColumnModel columnModel = tbl_show_menu_items.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(200); // First Name column
        columnModel.getColumn(1).setPreferredWidth(10); // Last Name column
        TableColumnModel columnMode2 = tbl_show_cart.getColumnModel();
        columnMode2.getColumn(0).setPreferredWidth(180); // First Name column
        columnMode2.getColumn(1).setPreferredWidth(10); // Last Name column
        tbl_cart = (DefaultTableModel) tbl_show_cart.getModel();
        //insert products to linkedlist
        insertMenuDetails();
        
        // Add selection listener to sourceTable
        tbl_show_menu_items.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    updateTargetTable();
                }
            }
        });
        
        // this codes for the digital clock
        Thread t=new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        cmb_location = new javax.swing.JComboBox<>();
        btn_beverage = new rojeru_san.complementos.RSButtonHover();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_show_cart = new javax.swing.JTable();
        billvalue = new javax.swing.JPanel();
        lbl_total = new javax.swing.JLabel();
        btn_order_now = new rojeru_san.complementos.RSButtonHover();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_min_max_sort = new rojeru_san.complementos.RSButtonHover();
        btn_max_min_sort = new rojeru_san.complementos.RSButtonHover();
        btn_popularity_sort = new rojeru_san.complementos.RSButtonHover();
        btn_alphabetical_sort = new rojeru_san.complementos.RSButtonHover();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea_display = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txt_customer_telephone = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_show_menu_items = new javax.swing.JTable();
        lbl_timeshow = new java.awt.Label();
        rSButtonHover1 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover5 = new rojeru_san.complementos.RSButtonHover();
        btn_pizza = new rojeru_san.complementos.RSButtonHover();
        btn_appetizer = new rojeru_san.complementos.RSButtonHover();
        btn_dessert = new rojeru_san.complementos.RSButtonHover();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmb_order_type = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lbl_time = new java.awt.Label();
        rSButtonHover7 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover9 = new rojeru_san.complementos.RSButtonHover();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home UI");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(156, 150, 150));
        jLabel22.setText("copyright ©PDSA | Develop By Hirantha And Liviru");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 990, -1, -1));

        cmb_location.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmb_location.setForeground(new java.awt.Color(204, 0, 0));
        cmb_location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nugegoda", "Wellampitiya" }));
        cmb_location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_locationActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_location, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 280, 50));

        btn_beverage.setBackground(new java.awt.Color(204, 0, 51));
        btn_beverage.setText("Beverage");
        btn_beverage.setColorHover(new java.awt.Color(0, 255, 51));
        btn_beverage.setColorTextHover(new java.awt.Color(0, 0, 0));
        btn_beverage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_beverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_beverageActionPerformed(evt);
            }
        });
        jPanel1.add(btn_beverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 130, 50));

        tbl_show_cart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_show_cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Price"
            }
        ));
        tbl_show_cart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_show_cart.setGridColor(new java.awt.Color(204, 204, 204));
        tbl_show_cart.setRowHeight(40);
        tbl_show_cart.setSelectionBackground(new java.awt.Color(204, 0, 51));
        tbl_show_cart.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tbl_show_cart.setShowGrid(true);
        tbl_show_cart.setShowVerticalLines(false);
        jScrollPane3.setViewportView(tbl_show_cart);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 70, 460, 500));

        billvalue.setBackground(new java.awt.Color(255, 255, 255));
        billvalue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        billvalue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_total.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lbl_total.setText("0.00");
        billvalue.add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 120, -1));

        btn_order_now.setBackground(new java.awt.Color(204, 0, 0));
        btn_order_now.setText("Order Now");
        btn_order_now.setColorHover(new java.awt.Color(0, 153, 0));
        btn_order_now.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_order_now.setIconTextGap(18);
        btn_order_now.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_order_nowActionPerformed(evt);
            }
        });
        billvalue.add(btn_order_now, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 240, 74));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel12.setText("Total");
        billvalue.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jPanel1.add(billvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 580, 460, 220));

        jPanel2.setBackground(new java.awt.Color(235, 232, 232));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_min_max_sort.setBackground(new java.awt.Color(0, 153, 0));
        btn_min_max_sort.setText("Min - Max");
        btn_min_max_sort.setColorHover(new java.awt.Color(204, 0, 0));
        btn_min_max_sort.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_min_max_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_min_max_sortActionPerformed(evt);
            }
        });
        jPanel2.add(btn_min_max_sort, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 120, 50));

        btn_max_min_sort.setBackground(new java.awt.Color(0, 153, 0));
        btn_max_min_sort.setText("Max - Min");
        btn_max_min_sort.setColorHover(new java.awt.Color(204, 0, 51));
        btn_max_min_sort.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_max_min_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_max_min_sortActionPerformed(evt);
            }
        });
        jPanel2.add(btn_max_min_sort, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 50));

        btn_popularity_sort.setBackground(new java.awt.Color(0, 153, 0));
        btn_popularity_sort.setText("Popular");
        btn_popularity_sort.setColorHover(new java.awt.Color(204, 0, 0));
        btn_popularity_sort.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_popularity_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_popularity_sortActionPerformed(evt);
            }
        });
        jPanel2.add(btn_popularity_sort, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, 50));

        btn_alphabetical_sort.setBackground(new java.awt.Color(0, 153, 0));
        btn_alphabetical_sort.setText("A - Z");
        btn_alphabetical_sort.setColorHover(new java.awt.Color(204, 0, 51));
        btn_alphabetical_sort.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_alphabetical_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alphabetical_sortActionPerformed(evt);
            }
        });
        jPanel2.add(btn_alphabetical_sort, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Filter By");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 330, 150));

        jPanel3.setBackground(new java.awt.Color(241, 237, 237));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textarea_display.setColumns(20);
        textarea_display.setRows(5);
        jScrollPane1.setViewportView(textarea_display);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 400, 240));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Display");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 420, 280));

        txt_customer_telephone.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_customer_telephone.setText("+94");
        txt_customer_telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_customer_telephoneActionPerformed(evt);
            }
        });
        jPanel1.add(txt_customer_telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 320, 50));

        tbl_show_menu_items.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_show_menu_items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Price"
            }
        ));
        tbl_show_menu_items.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_show_menu_items.setGridColor(new java.awt.Color(204, 204, 204));
        tbl_show_menu_items.setRowHeight(40);
        tbl_show_menu_items.setSelectionBackground(new java.awt.Color(204, 0, 51));
        tbl_show_menu_items.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tbl_show_menu_items.setShowGrid(true);
        tbl_show_menu_items.setShowVerticalLines(false);
        jScrollPane4.setViewportView(tbl_show_menu_items);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 580, 740));

        lbl_timeshow.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_timeshow.setForeground(new java.awt.Color(204, 0, 0));
        lbl_timeshow.setText("11.07.00AM");
        jPanel1.add(lbl_timeshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 10, -1, 40));

        rSButtonHover1.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonHover1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selfordering/apllication/chef (2).png"))); // NOI18N
        rSButtonHover1.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonHover1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/selfordering/apllication/chef (3).png"))); // NOI18N
        rSButtonHover1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/selfordering/apllication/chef (3).png"))); // NOI18N
        jPanel1.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 10, 60, -1));

        rSButtonHover5.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonHover5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selfordering/apllication/setting (2).png"))); // NOI18N
        rSButtonHover5.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonHover5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/selfordering/apllication/setting (3).png"))); // NOI18N
        jPanel1.add(rSButtonHover5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1850, 10, 60, -1));

        btn_pizza.setBackground(new java.awt.Color(204, 0, 51));
        btn_pizza.setText("Pizza");
        btn_pizza.setColorHover(new java.awt.Color(0, 255, 51));
        btn_pizza.setColorTextHover(new java.awt.Color(0, 0, 0));
        btn_pizza.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pizzaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 50));

        btn_appetizer.setBackground(new java.awt.Color(204, 0, 51));
        btn_appetizer.setText("Appetizer");
        btn_appetizer.setColorHover(new java.awt.Color(0, 255, 51));
        btn_appetizer.setColorTextHover(new java.awt.Color(0, 0, 0));
        btn_appetizer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_appetizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_appetizerActionPerformed(evt);
            }
        });
        jPanel1.add(btn_appetizer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 50));

        btn_dessert.setBackground(new java.awt.Color(204, 0, 51));
        btn_dessert.setText("Dessert");
        btn_dessert.setColorHover(new java.awt.Color(0, 255, 51));
        btn_dessert.setColorTextHover(new java.awt.Color(0, 0, 0));
        btn_dessert.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_dessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dessertActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dessert, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 140, 50));

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("copyright ©PDSA | Develop By Hirantha And Liviru");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 1060, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selfordering/apllication/output-onlinepngtools.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 210, 100));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Location");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Customer Telephone");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, -1, -1));

        cmb_order_type.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmb_order_type.setForeground(new java.awt.Color(204, 0, 0));
        cmb_order_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dine In", "Take Away", "Delivery", " " }));
        jPanel1.add(cmb_order_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 280, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Order Type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, -1));

        lbl_time.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(204, 0, 0));
        lbl_time.setText("11.07.00AM");
        jPanel1.add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, -1, 40));

        rSButtonHover7.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonHover7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selfordering/apllication/chef (2).png"))); // NOI18N
        rSButtonHover7.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonHover7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/selfordering/apllication/chef (3).png"))); // NOI18N
        rSButtonHover7.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/selfordering/apllication/chef (3).png"))); // NOI18N
        jPanel1.add(rSButtonHover7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 10, 60, -1));

        rSButtonHover9.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonHover9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selfordering/apllication/setting (2).png"))); // NOI18N
        rSButtonHover9.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonHover9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/selfordering/apllication/setting (3).png"))); // NOI18N
        jPanel1.add(rSButtonHover9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 10, 60, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(156, 150, 150));
        jLabel24.setText("copyright ©PDSA | Develop By Hirantha And Liviru");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 800, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_beverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_beverageActionPerformed
        // TODO add your handling code here:
        addBeverageToTableOriginal();
        pizza_button_state = false;
        appetizer_button_state = false;
        beverage_button_state = true;
        dessert_button_state = false;
    }//GEN-LAST:event_btn_beverageActionPerformed

    private void btn_order_nowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_order_nowActionPerformed

    }//GEN-LAST:event_btn_order_nowActionPerformed

    private void btn_min_max_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_min_max_sortActionPerformed
        // TODO add your handling code here:
        if(pizza_button_state == true)  //if pizza button is clicked, sort the pizza details
        {
            // Reset the pizza list to its original state
            menu_list.head = copyMenuItemLinkedList(original_menu_list.head);
            menu_list.mergeSortMinMax();
            addPizzaToTable();
        }
        else if(appetizer_button_state == true) //if appetizer button is clicked, sort the appetizer details
        {
            // Reset the pizza list to its original state
            menu_list.head = copyMenuItemLinkedList(original_menu_list.head);
            menu_list.mergeSortMinMax();
            addAppetizerToTable();
        }
        else if(beverage_button_state == true)  //if the beverage button is clicked, sort the beverage details
        {
            // Reset the pizza list to its original state
            menu_list.head = copyMenuItemLinkedList(original_menu_list.head);
            menu_list.mergeSortMinMax();
            addBeverageToTable();
        }
        else if(dessert_button_state == true)   //if the dessert button is clicked, sort the dessert details
        {
            // Reset the pizza list to its original state
            menu_list.head = copyMenuItemLinkedList(original_menu_list.head);
            menu_list.mergeSortMinMax();
            addDessertToTable();
        }
    }//GEN-LAST:event_btn_min_max_sortActionPerformed

    private void btn_max_min_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_max_min_sortActionPerformed
        // TODO add your handling code here:
        if(pizza_button_state == true)  //if pizza button is clicked, sort the pizza details
        {
            // Reset the pizza list to its original state
            menu_list.head = copyMenuItemLinkedList(original_menu_list.head);
            menu_list.mergeSortMaxMin();
            addPizzaToTable();
        }
        else if(appetizer_button_state == true) //if appetizer button is clicked, sort the appetizer details
        {
            // Reset the pizza list to its original state
            menu_list.head = copyMenuItemLinkedList(original_menu_list.head);
            menu_list.mergeSortMaxMin();
            addAppetizerToTable();
        }
        else if(beverage_button_state == true)  //if the beverage button is clicked, sort the beverage details
        {
            // Reset the pizza list to its original state
            menu_list.head = copyMenuItemLinkedList(original_menu_list.head);
            menu_list.mergeSortMaxMin();
            addBeverageToTable();
        }
        else if(dessert_button_state == true)   //if the dessert button is clicked, sort the dessert details
        {
            // Reset the pizza list to its original state
            menu_list.head = copyMenuItemLinkedList(original_menu_list.head);
            menu_list.mergeSortMaxMin();
            addDessertToTable();
        }
    }//GEN-LAST:event_btn_max_min_sortActionPerformed

    private void btn_popularity_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_popularity_sortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_popularity_sortActionPerformed

    private void btn_alphabetical_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alphabetical_sortActionPerformed
        // TODO add your handling code here:
        if(pizza_button_state == true)  //if pizza button is clicked, sort the pizza details
        {
            // Reset the pizza list to its original state
            menu_list.head = copyMenuItemLinkedList(original_menu_list.head);
            menu_list.mergeSortAlphabetical();
            addPizzaToTable();
        }
        else if(appetizer_button_state == true) //if appetizer button is clicked, sort the appetizer details
        {
            // Reset the pizza list to its original state
            menu_list.head = copyMenuItemLinkedList(original_menu_list.head);
            menu_list.mergeSortAlphabetical();
            addAppetizerToTable();
        }
        else if(beverage_button_state == true)  //if the beverage button is clicked, sort the beverage details
        {
            // Reset the pizza list to its original state
            menu_list.head = copyMenuItemLinkedList(original_menu_list.head);
            menu_list.mergeSortAlphabetical();
            addBeverageToTable();
        }
        else if(dessert_button_state == true)   //if the dessert button is clicked, sort the dessert details
        {
            // Reset the pizza list to its original state
            menu_list.head = copyMenuItemLinkedList(original_menu_list.head);
            menu_list.mergeSortAlphabetical();
            addDessertToTable();
        }
    }//GEN-LAST:event_btn_alphabetical_sortActionPerformed

    private void txt_customer_telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_customer_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_customer_telephoneActionPerformed

    private void btn_pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pizzaActionPerformed
        // TODO add your handling code here:
        addPizzaToTableOriginal();
        pizza_button_state = true;
        appetizer_button_state = false;
        beverage_button_state = false;
        dessert_button_state = false;
    }//GEN-LAST:event_btn_pizzaActionPerformed

    private void btn_appetizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_appetizerActionPerformed
        // TODO add your handling code here:
        addAppetizerToTableOriginal();
        pizza_button_state = false;
        appetizer_button_state = true;
        beverage_button_state = false;
        dessert_button_state = false;
    }//GEN-LAST:event_btn_appetizerActionPerformed

    private void btn_dessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dessertActionPerformed
        // TODO add your handling code here:
        addDessertToTableOriginal();
        pizza_button_state = false;
        appetizer_button_state = false;
        beverage_button_state = false;
        dessert_button_state = true;
    }//GEN-LAST:event_btn_dessertActionPerformed

    private void cmb_locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_locationActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel billvalue;
    private rojeru_san.complementos.RSButtonHover btn_alphabetical_sort;
    private rojeru_san.complementos.RSButtonHover btn_appetizer;
    private rojeru_san.complementos.RSButtonHover btn_beverage;
    private rojeru_san.complementos.RSButtonHover btn_dessert;
    private rojeru_san.complementos.RSButtonHover btn_max_min_sort;
    private rojeru_san.complementos.RSButtonHover btn_min_max_sort;
    private rojeru_san.complementos.RSButtonHover btn_order_now;
    private rojeru_san.complementos.RSButtonHover btn_pizza;
    private rojeru_san.complementos.RSButtonHover btn_popularity_sort;
    private javax.swing.JComboBox<String> cmb_location;
    private javax.swing.JComboBox<String> cmb_order_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private java.awt.Label lbl_time;
    private java.awt.Label lbl_timeshow;
    private javax.swing.JLabel lbl_total;
    private rojeru_san.complementos.RSButtonHover rSButtonHover1;
    private rojeru_san.complementos.RSButtonHover rSButtonHover5;
    private rojeru_san.complementos.RSButtonHover rSButtonHover7;
    private rojeru_san.complementos.RSButtonHover rSButtonHover9;
    private javax.swing.JTable tbl_show_cart;
    private javax.swing.JTable tbl_show_menu_items;
    private javax.swing.JTextArea textarea_display;
    private javax.swing.JTextField txt_customer_telephone;
    // End of variables declaration//GEN-END:variables
    @Override
    public void run() 
    {
         while (true)
        {
            Calendar cal=Calendar.getInstance();
            hour=cal.get(Calendar.HOUR_OF_DAY);
            minute=cal.get(Calendar.MINUTE);
            second=cal.get(Calendar.SECOND); 
            SimpleDateFormat sdf12 =new SimpleDateFormat("hh:mm:ss aa");
            Date dat =cal.getTime();
            String time12=sdf12.format(dat);
            lbl_time.setText(time12);
        }
    }
    //method implementation at the bottom
    //insert Menu details
    public void insertMenuDetails()
    {
        //insert 10 pizza details
        menu_list.insertProducts("Chicken Pizza","Pizza", 1200.00, 500, 32);
        menu_list.insertProducts("Beef Pepperoni Pizza", "Pizza", 1100.00, 200,35);
        menu_list.insertProducts("Butter Chicken Pizza", "Pizza", 1600.00, 1000, 20);
        menu_list.insertProducts("Paneer Pizza", "Pizza", 990.00, 450, 25);
        menu_list.insertProducts("Sausage Delight Pizza", "Pizza", 1350.00, 350, 20);
        menu_list.insertProducts("Italian Pizza", "Pizza", 1450.00, 650, 33);
        menu_list.insertProducts("Pork Pizza", "Pizza", 2200.00, 100, 36);
        menu_list.insertProducts("Italian Veggie Pizza", "Pizza", 1000.00, 1500, 15);
        menu_list.insertProducts("American Spicy Pizza", "Pizza", 1150.00, 4050, 16);
        menu_list.insertProducts("Dominoes Pizza", "Pizza", 1800.00, 2100, 21);
        
        //insert 5 Appetizers
        menu_list.insertProducts("French Fries", "Appetizer", 300.00, 1000, 35);
        menu_list.insertProducts("Garlic Bread", "Appetizer", 350.00, 2000, 32);
        menu_list.insertProducts("Chicken Nuggets", "Appetizer", 200.00, 1100, 20);
        menu_list.insertProducts("Chicken Wings", "Appetizer", 150.00, 900, 18);
        menu_list.insertProducts("Cheese and Chicken balls", "Appetizer", 220.00, 960, 17);
        
        //insert 10 beverages details
        menu_list.insertProducts("Mineral Water", "Beverage", 300.00, 5400, 32);
        menu_list.insertProducts("Coca Cola", "Beverage", 1100.00, 5000, 23);
        menu_list.insertProducts("Cappuccino", "Beverage", 1200.00, 4500, 25);
        menu_list.insertProducts("Iced Coffee", "Beverage", 900.00, 3050, 31);
        menu_list.insertProducts("Strawberry Milkshake", "Beverage", 1350.00, 1350, 23);
        
        //insert 10 dessert details
        menu_list.insertProducts("Raspberry Cheesecake", "Dessert", 700.00, 2000, 23);
        menu_list.insertProducts("Lava Cake", "Dessert", 750.00, 2200, 33);
        menu_list.insertProducts("English Custard", "Dessert", 900.00, 1150, 32);
        menu_list.insertProducts("Chocolate Brownies", "Dessert", 850.00, 930, 21);
        menu_list.insertProducts("Fruit Torte", "Dessert", 1020.00, 965, 22);
        
        // Store the original pizza list
        original_menu_list.head = copyMenuItemLinkedList(menu_list.head);
    }
    public MenuItemNode copyMenuItemLinkedList(MenuItemNode head) 
    {
        MenuItemNode newHead = null;
        MenuItemNode tail = null;
        MenuItemNode current = head;
        
        while (current != null) 
        {
            MenuItemNode newNode = new MenuItemNode(current.getName(), current.getCategory(), current.getPrice(), current.getPopularity(), current.getPreparationTime());
            if (newHead == null) 
            {
                newHead = newNode;
                tail = newNode;
            } 
            else 
            {
                tail.next = newNode;
                newNode.previous = tail;
                tail = newNode;
            }
            current = current.next;
        }
        return newHead;
    }
    //method to display the Pizza products when Pizza button is pressed
    public void addPizzaToTable()
    {
        DefaultTableModel tbl_items = (DefaultTableModel) tbl_show_menu_items.getModel();
        tbl_items.setRowCount(0);
        MenuItemNode current_product = menu_list.head;
        
        while(current_product != null)
        {
            if(current_product.getCategory().equals("Pizza"))
            {
                tbl_items.addRow(new Object[]{current_product.getName(), current_product.getPrice()});
            }
            current_product = current_product.next;
        }
    }
    public void addPizzaToTableOriginal()
    {
        MenuItemNode current_product = original_menu_list.head;
        DefaultTableModel tbl_items = (DefaultTableModel) tbl_show_menu_items.getModel();
        tbl_items.setRowCount(0);
        
        while(current_product != null)
        {
            if(current_product.getCategory().equals("Pizza"))
            {
                tbl_items.addRow(new Object[]{current_product.getName(), current_product.getPrice()});
            }
            current_product = current_product.next;
        }
    }
    //method to display the Appetizer products when appetizer button is pressed
    public void addAppetizerToTable()
    {
        DefaultTableModel tbl_items = (DefaultTableModel) tbl_show_menu_items.getModel();
        tbl_items.setRowCount(0);
        MenuItemNode current_product = menu_list.head;
        
        while(current_product != null)
        {
            if(current_product.getCategory().equals("Appetizer"))
            {
                tbl_items.addRow(new Object[]{current_product.getName(), current_product.getPrice()});
            }
            current_product = current_product.next;
        }
    }
    public void addAppetizerToTableOriginal()
    {
        MenuItemNode current_product = original_menu_list.head;
        DefaultTableModel tbl_items = (DefaultTableModel) tbl_show_menu_items.getModel();
        tbl_items.setRowCount(0);
        
        while(current_product != null)
        {
            if(current_product.getCategory().equals("Appetizer"))
            {
                tbl_items.addRow(new Object[]{current_product.getName(), current_product.getPrice()});
            }
            current_product = current_product.next;
        }
    }
    //method to display the Beverage products when beverage button is pressed
    public void addBeverageToTable()
    {
        DefaultTableModel tbl_items = (DefaultTableModel) tbl_show_menu_items.getModel();
        tbl_items.setRowCount(0);
        MenuItemNode current_product = menu_list.head;
        
        while(current_product != null)
        {
            if(current_product.getCategory().equals("Beverage"))
            {
                tbl_items.addRow(new Object[]{current_product.getName(), current_product.getPrice()});
            }
            current_product = current_product.next;
        }
    }
    public void addBeverageToTableOriginal()
    {
        MenuItemNode current_product = original_menu_list.head;
        DefaultTableModel tbl_items = (DefaultTableModel) tbl_show_menu_items.getModel();
        tbl_items.setRowCount(0);
        
        while(current_product != null)
        {
            if(current_product.getCategory().equals("Beverage"))
            {
                tbl_items.addRow(new Object[]{current_product.getName(), current_product.getPrice()});
            }
            current_product = current_product.next;
        }
    }
    //method to display the Dessert products when Dessert button is pressed
    public void addDessertToTable()
    {
        DefaultTableModel tbl_items = (DefaultTableModel) tbl_show_menu_items.getModel();
        tbl_items.setRowCount(0);
        MenuItemNode current_product = menu_list.head;
        
        while(current_product != null)
        {
            if(current_product.getCategory().equals("Dessert"))
            {
                tbl_items.addRow(new Object[]{current_product.getName(), current_product.getPrice()});
            }
            current_product = current_product.next;
        }
    }
    public void addDessertToTableOriginal()
    {
        MenuItemNode current_product = original_menu_list.head;
        DefaultTableModel tbl_items = (DefaultTableModel) tbl_show_menu_items.getModel();
        tbl_items.setRowCount(0);
        
        while(current_product != null)
        {
            if(current_product.getCategory().equals("Dessert"))
            {
                tbl_items.addRow(new Object[]{current_product.getName(), current_product.getPrice()});
            }
            current_product = current_product.next;
        }
    }
    public void updateTargetTable()
    {
        int selectedRow = tbl_show_menu_items.getSelectedRow();
        if (selectedRow != -1) 
        {
            if(pizza_button_state == true)
            {
                passPizzaPreparationTimeToHeap(selectedRow);
            }
            else if(appetizer_button_state == true)
            {
                passAppetizerPreparationTimeToHeap(selectedRow);
            }
            else if(beverage_button_state == true)
            {
                passBeveragePreparationTimeToHeap(selectedRow);
            }
            else if(dessert_button_state == true)
            {
                passDessertPreparationTimeToHeap(selectedRow);
            }
            //codes to pass the values from table 1 to table 2
            String itemName = tbl_show_menu_items.getValueAt(selectedRow, 0).toString();
            double price = Double.parseDouble(tbl_show_menu_items.getValueAt(selectedRow, 1).toString());

            // Add selected row to target table
            Object[] rowData = {itemName, price};
            tbl_cart.addRow(rowData);
            
            //update the total 
            updateTotalLabel();
        }
    }
    //calculate and display the order total
    public void updateTotalLabel() 
    {
        double total = 0.0;
        for (int row = 0; row < tbl_cart.getRowCount(); row++) {
            double price = Double.parseDouble(tbl_cart.getValueAt(row, 1).toString());
            total += price;
        }
        lbl_total.setText(String.valueOf(total));
    }
    //pass the pizza preparation time to heap
    public void passPizzaPreparationTimeToHeap(int selectedRow)
    {
        String pizza_name = String.valueOf(tbl_show_menu_items.getValueAt(selectedRow, 0));
        MenuItemNode selected_pizza = original_menu_list.head;
        while(selected_pizza != null)
        {
            if(pizza_name.equals(selected_pizza.getName()))
            {
                System.out.println("Pizza prep time: " + selected_pizza.getPreparationTime());
                max_heap.insert(selected_pizza.getPreparationTime());
            }
            selected_pizza = selected_pizza.next;
        }
    }
    //pass the appetizer preparation time to heap
    public void passAppetizerPreparationTimeToHeap(int selectedRow)
    {
        String appetizer_name = String.valueOf(tbl_show_menu_items.getValueAt(selectedRow, 0));
        MenuItemNode selected_appetizer = original_menu_list.head;
        while(selected_appetizer != null)
        {
            if(appetizer_name.equals(selected_appetizer.getName()))
            {
                System.out.println("Appetizer prep time: " + selected_appetizer.getPreparationTime());
                max_heap.insert(selected_appetizer.getPreparationTime());
            }
            selected_appetizer = selected_appetizer.next;
        }
    }
    //pass the beverage preparation time to heap
    public void passBeveragePreparationTimeToHeap(int selectedRow)
    {
        String beverage_name = String.valueOf(tbl_show_menu_items.getValueAt(selectedRow, 0));
        MenuItemNode selected_beverage = original_menu_list.head;
        while(selected_beverage != null)
        {
            if(beverage_name.equals(selected_beverage.getName()))
            {
                System.out.println("Beverage prep time: " + selected_beverage.getPreparationTime());
                max_heap.insert(selected_beverage.getPreparationTime());
            }
            selected_beverage = selected_beverage.next;
        }
    }
    //pass the beverage preparation time to heap
    public void passDessertPreparationTimeToHeap(int selectedRow)
    {
        String dessert_name = String.valueOf(tbl_show_menu_items.getValueAt(selectedRow, 0));
        MenuItemNode selected_dessert = original_menu_list.head;
        while(selected_dessert != null)
        {
            if(dessert_name.equals(selected_dessert.getName()))
            {
                System.out.println("Dessert prep time: " + selected_dessert.getPreparationTime());
                max_heap.insert(selected_dessert.getPreparationTime());
            }
            selected_dessert = selected_dessert.next;
        }
    }
}
